### ISSUE TITLE
Eleventastic errors on build

### ISSUE THREAD

**Issue by djmtype** [maxboeck/eleventastic#27]
@maxboeck I have no issues when running in dev, but on build I get the error below. Mind you, all I did was clone this repo and didn't touch any files. 

I am running an M1 Mac with Node 15.x.

```
❯ npm run build

> eleventastic@1.0.0 build
> run-s clean eleventy:prod --print-label

[clean        ] 
[clean        ] > eleventastic@1.0.0 clean
[clean        ] > del-cli dist
[clean        ] 
[eleventy:prod] 
[eleventy:prod] > eleventastic@1.0.0 eleventy:prod
[eleventy:prod] > cross-env ELEVENTY_ENV=production eleventy
[eleventy:prod] 
[eleventy:prod] Writing dist/build.txt from ./src/build.njk.
[eleventy:prod] Writing dist/feed.xml from ./src/feed.njk.
[eleventy:prod] Writing dist/robots.txt from ./src/robots.njk.
[eleventy:prod] Writing dist/serviceworker.js from ./src/serviceworker.njk.
[eleventy:prod] Writing dist/sitemap.xml from ./src/sitemap.njk.
[eleventy:prod] Writing dist/assets/scripts/main.js from ./src/assets/scripts/__scripts.11ty.js.
[eleventy:prod] Writing dist/assets/styles/main.css from ./src/assets/styles/__styles.11ty.js.
[eleventy:prod] Writing dist/404/index.html from ./src/404.njk.
[eleventy:prod] Writing dist/about/index.html from ./src/pages/about.njk.
[eleventy:prod] Writing dist/offline/index.html from ./src/pages/offline.njk.
[eleventy:prod] Writing dist/posts/2020-04-12-sample-post/index.html from ./src/posts/2020-04-12-sample-post.md.
[eleventy:prod] Writing dist/index.html from ./src/index.njk.
[eleventy:prod] Unhandled rejection in promise ([object Promise]): (more in DEBUG output)
[eleventy:prod] > The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[eleventy:prod] 
[eleventy:prod] `TypeError` was thrown:
[eleventy:prod]     TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
[eleventy:prod]         at writeFile (node:fs:1499:5)
[eleventy:prod]         at go$writeFile (/Volumes/Evo/Sites/eleventastic/node_modules/graceful-fs/graceful-fs.js:138:14)
[eleventy:prod]         at Object.writeFile (/Volumes/Evo/Sites/eleventastic/node_modules/graceful-fs/graceful-fs.js:135:12)
[eleventy:prod]         at /Volumes/Evo/Sites/eleventastic/node_modules/fs-extra/lib/output/index.js:18:27
[eleventy:prod]         at /Volumes/Evo/Sites/eleventastic/node_modules/universalify/index.js:23:46
```

**Comment by kuwts** [comment]
Did you end up finding a solution to this? Having the same issue

**Comment by djmtype** [comment]
I haven't. It's been years since this theme has been updated, too. Another thing that really stands out is the node sass dependency which is deprecated and seems incompatible with Mac ARM chips based on my experience with other projects.
